services:
  fastify-app:
    build: ./fastify
    ports:
      - "8080"
    volumes:
      - ./fastify:/app # local project folder into container
      - /app/node_modules # prevent overwriting node_modules
    working_dir: /app
    command: npm run dev # run with hot reload
    